<?php

namespace MadeiraMadeiraBr\HttpClient;

interface EnvConfigInterface
{
    const CURLOPT_CONNECTTIMEOUT = 'HTTP_CLIENT_CURLOPT_USERAGENT';
    const CURLOPT_TIMEOUT_MS = 'HTTP_CLIENT_CURLOPT_TIMEOUT_MS';
    const CURLOPT_USERAGENT = 'HTTP_CLIENT_CURLOPT_USERAGENT';
    const SLOW_REQUEST_ALERT = 'HTTP_CLIENT_SLOW_REQUEST_ALERT';
    const FALSE_POSITIVE_STATUS_ALERT = 'HTTP_CLIENT_FALSE_POSITIVE_STATUS_ALERT';
    const UNEXPECTED_RESPONSE_STATUS_ALERT = 'HTTP_CLIENT_UNEXPECTED_RESPONSE_STATUS_ALERT';
}